# Generated by Django 6.0.4 on 2026-04-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_category_remove_book_genre_book_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, to='books.category'),
        ),
    ]
