# Generated by Django 6.0.4 on 2026-04-15 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_book_image_alter_book_isbn_10_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookimage',
            options={'ordering': ['-is_primary', 'id']},
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_10',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN-10 must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn_13',
            field=models.CharField(max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN-13 must be exactly 13 digits.', regex='^\\d{13}$')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(null=True),
        ),
    ]
