# Generated by Django 6.0.4 on 2026-04-23 20:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_bookimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
