# Generated by Django 6.0.4 on 2026-04-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0011_alter_bookimage_options_alter_book_isbn_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, to='books.book'),
        ),
    ]
