# Generated by Django 6.0.4 on 2026-04-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useractivity_options_and_more'),
        ('books', '0011_alter_bookimage_options_alter_book_isbn_10_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='useractivity',
            name='accounts_us_user_id_ccfedd_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivity',
            name='accounts_us_timesta_7c259d_idx',
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, related_name='favored_by', to='books.book'),
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
