# Generated by Django 6.0.4 on 2026-04-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_user_review_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=50),
        ),
    ]
